### ISSUE TITLE
add option to render chart in terminal

### ISSUE THREAD

**Issue by fgeller** [marianogappa/chart#1]
as my main use case would be in a terminal, i'd prefer not to open a browser but get the gist of it right where i'm working with the data. horizontal bar chart would be best i guess?

**Comment by marianogappa** [comment]
@fgeller have you tried https://github.com/ryankscott/termchart?

Would you be interested in being able to set or know the name of the output file to rsync it to some other box you'd have the browser on? Maybe even a feature to rsync on creation?

I may consider terminal charting in the future if there are many requests.

**Comment by fgeller** [comment]
yeah, using termchart only now.
