### ISSUE TITLE
Size issue with pie charts since Chart.js upgrade

### ISSUE THREAD

**Issue by marianogappa** [marianogappa/chart#25]
Pie charts exceed viewport after updating Chart.js to 2.6.

We've looked into it briefly with no success. Since pie charts have very disimilar aspect ratio constraints compared to all other charts, unless anyone has a better idea I will simply conditionally just use half the viewport when it's a pie chart to solve this.

**Comment by marianogappa** [comment]
cf https://github.com/chartjs/Chart.js/issues/2958
https://github.com/chartjs/Chart.js/issues/882

**Comment by marianogappa** [comment]
This looks good enough; both chart kinds show up completely on the viewport on Chrome, Firefox and Safari (on my unmodified installs).

**Comment by SiddheshShinde-tech** [comment]
@marianogappa My Pie chart completely shrinks up in Mobile View. 
Current Options - 
responsive: true, maintainaspectratio: false

HTML Code - 
<div
          class="wrapper" style="position: relative; height: 70vh"
        >
          <canvas id="myChart"></canvas>
        </div>

I even tried resizing the parent class of the canvas but that's not working at all. Please help me out.

Mobile View - 
![Screen Shot 2021-01-23 at 14 31 19](https://user-images.githubusercontent.com/62283380/105574074-1e497c80-5d88-11eb-85a8-e1401801e811.png)

Desktop View - 
![Screen Shot 2021-01-23 at 12 44 15](https://user-images.githubusercontent.com/62283380/105574084-33bea680-5d88-11eb-9d32-8232f722ec58.png)
