### ISSUE TITLE
Support more colors

### ISSUE THREAD

**Issue by moonranger** [marianogappa/chart#27]
When there are a lot of lines/bars etc in a chart, the same color gets reused, which can make it hard to read.

**Comment by marianogappa** [comment]
Could use this list as a guide
https://gist.github.com/leodido/c08577236b46834e5ba181450046e95b

Unfortunately I don't know where I got the original color palette from. It'd be great to document it this time.

**Comment by marianogappa** [comment]
@moonranger your colours are ready thanks to @Kuraio :) You may `go get` now or wait for a release soon.
