### ISSUE TITLE
Code structure makes it hard to contribute

### ISSUE THREAD

**Issue by marianogappa** [marianogappa/chart#34]
As the codebase grew, the structure became unwieldy for modifications.

**Comment by szaydel** [comment]
When I browse over the source, a couple of things I feel could be improved along the lines of this issue.  Names of fields and variables are a bit cryptic and little commentary exists. It may seem tedious and not very beneficial, but I think small improvements to these two could be very beneficial to those looking to contribute in some way.

**Comment by marianogappa** [comment]
Code should be a lot more approachable now. Will be considering further improvements in the future, in order to make it easy for devs to use `chart` programatically, by importing the packages.
